### PR TITLE
Fix typo in expandIndexed

### PR DESCRIPTION
**Pull request by natebosch**

### CODE REVIEW

**Review by jakemac53 — APPROVED** [review]
I assume this hasn't yet been released?

**Comment by natebosch** [comment]
It hasn't been, but now it is.

My inclination is to just go with it. The only broken release is a `-nullsafety.4` and fixing this now should limit the exposure.

WDYT?

**Comment by lrhn** [comment]
LGTM, thanks and sorry.
(And obviously it happened to a method which existed on `Iterable` with the same behavior, because otherwise it would have been very visible).

**Comment by jakemac53** [comment]
Yes I am fine with just fixing this since we are still in pre-release

**Pull request merged**
