### PR TITLE
Add ListExtensions.firstOrNull, lastOrNull, singleOrNull.

### PR DESCRIPTION
**Pull request by scheglov**

### CODE REVIEW

**Comment by natebosch** [comment]
@lrhn - should we define these in the SDK instead?

**Comment by scheglov** [comment]
This is not urgent at all, but it would be nice to get some reaction to it :-)

**Comment by natebosch** [comment]
I like the APIs. I think it would be worth moving to the SDK since that is where the definitions are for `Iterable`. Unless @lrhn has concerns I'd be inclined to close this and reopen as a CL in the SDK.

**Comment by lrhn** [comment]
SGTM, move it!

**Comment by natebosch** [comment]
@scheglov - do you want to open a CL in the SDK or should I?

**Comment by scheglov** [comment]
I opened https://github.com/dart-lang/sdk/issues/53756

**Pull request closed without merging**
