### PR TITLE
Correct DeepCollectionEquality documentation

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
That cost me a few, yikes.

### CODE REVIEW

**Comment by lrhn** [comment]
I actually think `DeepCollectionEquality` should work to arbitrary depths. If it doesn't work, that's a bug in the implementation, not the documentation.

**Comment by creativecreatorormaybenot** [comment]
@lrhn Yes, I thought so too. However, I wanted to believe that the implementation was intentional 😶

**Comment by natebosch** [comment]
I cannot reproduce the bug. Do you have sample code that demonstrates `DeepCollectionEquality` only working to a depth of 1?

**Comment by creativecreatorormaybenot** [comment]
@natebosch Just look at the code? 😄

It will e.g. use a `ListEquality` for lists in the root collection (but it should obviously use another `DeepCollectionEquality` for recursion, which does not work atm).

Example:

```dart
final list = [
  [
     [1, 2],
  ].
];
final list2 = [
  [
     [1, 2],
  ].
];

const DeepCollectionEquality().equals(list1, list2); // false
```

**Comment by creativecreatorormaybenot** [comment]
@natebosch You just need to take a look at the source code 😄

It will e.g. use a `ListEquality` for lists in the root collection (but it should obviously use another `DeepCollectionEquality` for recursion, which does not work atm).

Example:

```dart
final list = [
  [
     [1, 2],
  ].
];
final list2 = [
  [
     [1, 2],
  ].
];

const DeepCollectionEquality().equals(list1, list2); // false
```

**Comment by creativecreatorormaybenot** [comment]
@natebosch You just need to take a look at the source code 😄

It will e.g. use a `ListEquality` for lists in the root collection (but it should obviously use another `DeepCollectionEquality` for recursion, which does not work atm).

Example:

```dart
final list = [
  [
     [1, 2],
  ],
];
final list2 = [
  [
     [1, 2],
  ],
];

const DeepCollectionEquality().equals(list1, list2); // false
```

**Comment by natebosch** [comment]
You example works for me on the master branch. Which version of the package are you using?

If you concern is this line of code:

https://github.com/dart-lang/collection/blob/80f5b6de8a8d8d584732a71bb59912da3e44883b/lib/src/equality.dart#L449

This is the correct implementation for arbitrary depth. Specifically the `this` argument to `ListEquality(this)` ensures that each element is compared also with `DeepCollectionEquality`.

Closing for now since this looks like a misunderstanding.

**Comment by creativecreatorormaybenot** [comment]
@natebosch Thanks 👍🏽

I will need to figure out why it did not work for me. This can stay closed until then.

**Pull request closed without merging**
