### PR TITLE
Travis: test oldest support SDK

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
> Wait, this looks like it changes the testing significantly also?

@matanlurey set these all up to run DDC back when we didn't have strong mode everywhere else.

Now that we're past those days, cleaning this up substantially.

**Comment by jakemac53** [comment]
This also drops the stages and runs the tests without build_runner right?

I would instead keep the stages and run the tests with DDC only (if we want to run web tests at all).

We could also add build_vm_compilers for running vm tests faster.

**Comment by kevmoo** [comment]
I was trying to make things a bit more simple by testing in the standard
way.

Most of our other packages don't go through this dance.

**Comment by jakemac53** [comment]
> I was trying to make things a bit more simple by testing in the standard way.

Standardization is good, but we should be focused on doing the best thing not whatever all our other repos are doing, and moving forward into the future.

With the latest kernel stuff for everything, I get these times:

## time pub run  build_runner test -- -p vm -p chrome (full build)

note there is >5s of extra time here because pub isn't precompiling build_runner

```time pbr test -- -p chrome -p vm
[INFO] Generating build script completed, took 398ms
[INFO] Creating build script snapshot... completed, took 13.1s
[INFO] Building new asset graph completed, took 1.6s
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Running build completed, took 27.4s
[INFO] Caching finalized dependency graph completed, took 212ms
[INFO] Creating merged output dir `/tmp/build_runner_testTKPDYP/` completed, took 429ms
[INFO] Writing asset manifest completed, took 5ms
[INFO] Succeeded after 28.1s with 1926 outputs (4978 actions)
Running tests...

00:16 +2488: All tests passed!                                                                         

real	1m14.877s
user	1m56.704s
sys	0m10.263s
```

## time pub run  build_runner test -- -p vm -p chrome (incremental build)

```
time pbr test -- -p chrome -p vm
[INFO] Generating build script completed, took 390ms
[INFO] Reading cached asset graph completed, took 366ms
[INFO] Checking for updates since last build completed, took 782ms
[INFO] Running build completed, took 315ms
[INFO] Caching finalized dependency graph completed, took 204ms
[INFO] Creating merged output dir `/tmp/build_runner_testEVOFNV/` completed, took 260ms
[INFO] Writing asset manifest completed, took 7ms
[INFO] Succeeded after 815ms with 0 outputs (0 actions)
Running tests...

00:15 +2488: All tests passed!                                                                         

real	0m33.748s
user	0m31.289s
sys	0m3.423s
```

## time pub run test -p vm -p chrome

```
time pub run test -p chrome -p vm
00:06 +0: [Chrome] compiling test/algorithms_test.dart                                                  
Compiled 8,618,314 characters Dart to 1,070,720 characters JavaScript in 6.02 seconds
Dart file (/tmp/dart_test_OYPPUB/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_QTLMVE/algorithms_test.dart.browser_test.dart.js

00:06 +0: [Chrome] compiling test/functions_test.dart                                                   
Compiled 8,617,200 characters Dart to 1,099,433 characters JavaScript in 6.20 seconds
Dart file (/tmp/dart_test_SXTVXT/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_DLSLJM/functions_test.dart.browser_test.dart.js

00:07 +0: [Chrome] compiling test/wrapper_test.dart                                                     
test/wrapper_test.dart:37:3:
Hint: Overriding 'noSuchMethod' causes the compiler to generate more code and prevents the compiler from doing some optimizations.
Consider removing this 'noSuchMethod' implementation.
  noSuchMethod(Invocation i) {
  ^
test/wrapper_test.dart:55:3:
Hint: Overriding 'noSuchMethod' causes the compiler to generate more code and prevents the compiler from doing some optimizations.
Consider removing this 'noSuchMethod' implementation.
  noSuchMethod(Invocation actual) {
  ^
Compiled 8,649,854 characters Dart to 1,399,082 characters JavaScript in 7.38 seconds
Dart file (/tmp/dart_test_ANUOMA/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_WZFYMV/wrapper_test.dart.browser_test.dart.js

00:12 +136: [Chrome] compiling test/union_set_controller_test.dart                                      
Compiled 8,608,677 characters Dart to 1,041,279 characters JavaScript in 6.15 seconds
Dart file (/tmp/dart_test_HPRNSP/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_MKTLSZ/union_set_controller_test.dart.browser_test.dart.js

00:13 +137: [Chrome] compiling test/equality_test.dart                                                  
Compiled 8,616,447 characters Dart to 1,071,949 characters JavaScript in 6.21 seconds
Dart file (/tmp/dart_test_WGKAJP/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_RSNBQO/equality_test.dart.browser_test.dart.js

00:14 +159: [Chrome] compiling test/canonicalized_map_test.dart                                         
Compiled 8,614,017 characters Dart to 1,062,965 characters JavaScript in 6.25 seconds
Dart file (/tmp/dart_test_WAYAIJ/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_LECZXO/canonicalized_map_test.dart.browser_test.dart.js

00:19 +186: [Chrome] compiling test/union_set_test.dart                                                 
Compiled 8,613,628 characters Dart to 1,095,753 characters JavaScript in 6.13 seconds
Dart file (/tmp/dart_test_KROIWB/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_TWYYYD/union_set_test.dart.browser_test.dart.js

00:19 +186: [Chrome] compiling test/comparators_test.dart                                               
Compiled 8,610,403 characters Dart to 1,049,879 characters JavaScript in 5.81 seconds
Dart file (/tmp/dart_test_DVTBMN/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_UYFHCO/comparators_test.dart.browser_test.dart.js

00:20 +222: [Chrome] compiling test/combined_wrapper/list_test.dart                                     
Compiled 8,627,716 characters Dart to 1,158,031 characters JavaScript in 6.24 seconds
Dart file (/tmp/dart_test_FHCBMK/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_ABJVVV/list_test.dart.browser_test.dart.js

00:25 +335: [Chrome] compiling test/combined_wrapper/iterable_test.dart                                 
Compiled 8,609,602 characters Dart to 1,037,567 characters JavaScript in 6.09 seconds
Dart file (/tmp/dart_test_RZGHAM/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_PXZPGT/iterable_test.dart.browser_test.dart.js

00:25 +335: [Chrome] compiling test/combined_wrapper/map_test.dart                                      
Compiled 8,627,279 characters Dart to 1,045,047 characters JavaScript in 6.24 seconds
Dart file (/tmp/dart_test_BCJURD/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_QZCDUS/map_test.dart.browser_test.dart.js

00:27 +363: [Chrome] compiling test/unmodifiable_collection_test.dart                                   
Compiled 8,625,410 characters Dart to 1,191,089 characters JavaScript in 6.64 seconds
Dart file (/tmp/dart_test_YUXXHT/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_XYRUVG/unmodifiable_collection_test.dart.browser_test.dart.js

00:31 +713: [Chrome] compiling test/equality_set_test.dart                                              
Compiled 8,609,120 characters Dart to 1,038,751 characters JavaScript in 6.07 seconds
Dart file (/tmp/dart_test_PRMMJV/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_PHSTNR/equality_set_test.dart.browser_test.dart.js

00:32 +714: [Chrome] compiling test/iterable_zip_test.dart                                              
Compiled 8,612,037 characters Dart to 1,049,637 characters JavaScript in 5.96 seconds
Dart file (/tmp/dart_test_ADEDNK/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_QSIIHQ/iterable_zip_test.dart.browser_test.dart.js

00:34 +974: [Chrome] compiling test/ignore_ascii_case_test.dart                                         
Compiled 8,609,409 characters Dart to 1,022,237 characters JavaScript in 6.45 seconds
Dart file (/tmp/dart_test_NSEURD/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_CXEQVZ/ignore_ascii_case_test.dart.browser_test.dart.js

00:39 +1328: [Chrome] compiling test/queue_list_test.dart                                               
Compiled 8,617,610 characters Dart to 1,098,935 characters JavaScript in 7.45 seconds
Dart file (/tmp/dart_test_MJMYHU/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_TCCTRO/queue_list_test.dart.browser_test.dart.js

00:39 +1328: [Chrome] compiling test/priority_queue_test.dart                                           
Compiled 8,612,553 characters Dart to 1,089,957 characters JavaScript in 7.48 seconds
Dart file (/tmp/dart_test_UQYCVF/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_DDCDWX/priority_queue_test.dart.browser_test.dart.js

00:41 +1452: [Chrome] compiling test/equality_map_test.dart                                             
Compiled 8,608,632 characters Dart to 1,033,302 characters JavaScript in 6.50 seconds
Dart file (/tmp/dart_test_RXJXRA/runInBrowser.dart) compiled to JavaScript: /tmp/dart_test_JTZVTW/test_HSDWIO/equality_map_test.dart.browser_test.dart.js

00:46 +2488: All tests passed!                                                                          

real	0m53.608s
user	2m49.643s
sys	0m10.531s
```

The incremental builds are significantly faster - and I think on travis you would even see the initial build be faster because the user time is significantly less (`pub run test` is taking full advantage of my local machine) .

**Comment by kevmoo** [comment]
@jakemac53 PTAL

**Comment by jakemac53** [comment]
Also delete the `tool/travis.sh` now?

**Comment by kevmoo** [comment]
> Also delete the `tool/travis.sh` now?

done!

**Pull request merged**
